defaults: &defaults
  docker:
  - image: circleci/ruby:2.5.0-node-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
    - checkout
    - restore_cache:
        keys:
        - depralyzer-{{ checksum "Gemfile.lock" }}
        - depralyzer-
    - run:
        name: Bundle Install
        command: bundle check || bundle install
    - save_cache:
        key: depralyzer-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle
    - run:
        name: Setup CodeClimate test-reporter
        command: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
          chmod +x cc-test-reporter
    - type: shell
      command: |
        ./cc-test-reporter before-build
        bundle exec rspec --profile 10 \
                          --format RspecJunitFormatter \
                          --out test_results/rspec.xml \
                          --format progress \
                          $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
        ./cc-test-reporter format-coverage -t simplecov $CIRCLE_ARTIFACTS/coverage/.resultset.json
        ./cc-test-reporter upload-coverage
    - store_test_results:
        path: test_results

workflows:
  version: 2
  commit:
    jobs:
    - build

